name: Test and Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Run tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get Version from Git Tag (or commit if no tag)
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || git rev-parse HEAD)
        echo "::set-output name=version::$VERSION"
    - name: Build
      run: go build -ldflags "-X donetick.com/core/config.Version=${{ steps.get_version.outputs.version }} -X donetick.com/core/config.Commit=$(git rev-parse HEAD) -X donetick.com/core/config.Date=$(date +%Y-%m-%d)" -v ./...